// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Servo_Test

#ifndef _SERVO_TEST_UI_H
#define _SERVO_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_labe1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_labe3;
extern lv_obj_t * ui_angleValue;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_ServoPin;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label7;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label10;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label11;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label12;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
void ui_event_angleSlider(lv_event_t * e);
extern lv_obj_t * ui_angleSlider;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
