// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Servo_Test

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void zeroDegreeClick(lv_event_t * e);
void fortyFiveDegreesClick(lv_event_t * e);
void ninetyDegreesClick(lv_event_t * e);
void oneHundredAndEightyDegreesClick(lv_event_t * e);
void SliderChange(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
