// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Servo_Test

#include "ui.h"
#include "ui_interface.h"
#include <stdio.h>

void zeroDegreeClick(lv_event_t * e)
{
	// 发送消息到逻辑层设置舵机角度
	if (ui_servo_set_angle(0)) {
		lv_label_set_text_fmt(ui_angleValue, "%d °", 0);
		lv_slider_set_value(ui_angleSlider, 0, LV_ANIM_ON);
	} else {
		printf("Failed to set servo angle: %d\n", 0);
	}
	printf("Current servo angle: %d\n", 0);
}

void fortyFiveDegreesClick(lv_event_t * e)
{
	// 发送消息到逻辑层设置舵机角度
	if (ui_servo_set_angle(45)) {
		lv_label_set_text_fmt(ui_angleValue, "%d °", 45);
		lv_slider_set_value(ui_angleSlider, 45, LV_ANIM_ON);
	} else {
		printf("Failed to set servo angle: %d\n", 45);
	}
	printf("Current servo angle: %d\n", 45);
}

void ninetyDegreesClick(lv_event_t * e)
{
	// 发送消息到逻辑层设置舵机角度
	if (ui_servo_set_angle(90)) {
		lv_label_set_text_fmt(ui_angleValue, "%d °", 90);
		lv_slider_set_value(ui_angleSlider, 90, LV_ANIM_ON);
	} else {
		printf("Failed to set servo angle: %d\n", 90);
	}
	printf("Current servo angle: %d\n", 90);
}

void oneHundredAndEightyDegreesClick(lv_event_t * e)
{
	// 发送消息到逻辑层设置舵机角度
	if (ui_servo_set_angle(180)) {
		lv_label_set_text_fmt(ui_angleValue, "%d °", 180);
		lv_slider_set_value(ui_angleSlider, 180, LV_ANIM_ON);
	} else {
		printf("Failed to set servo angle: %d\n", 180);
	}
	printf("Current servo angle: %d\n", 180);
}

void SliderChange(lv_event_t * e)
{
	// Your code here
	lv_obj_t * slider = lv_event_get_target(e);
	int angle = lv_slider_get_value(slider);
	
	// 发送消息到逻辑层设置舵机角度
	if (ui_servo_set_angle(angle)) {
		lv_label_set_text_fmt(ui_angleValue, "%d °", angle);
	} else {
		printf("Failed to set servo angle: %d\n", angle);
	}
	printf("Current servo angle: %d\n", angle);
}
