// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Servo_Test

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 317);
    lv_obj_set_height(ui_Panel1, 37);
    lv_obj_set_x(ui_Panel1, -1);
    lv_obj_set_y(ui_Panel1, -101);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labe1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_labe1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labe1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labe1, 2);
    lv_obj_set_y(ui_labe1, 0);
    lv_obj_set_align(ui_labe1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labe1, "Servo Control");
    lv_obj_set_style_text_font(ui_labe1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 317);
    lv_obj_set_height(ui_Panel3, 37);
    lv_obj_set_x(ui_Panel3, -1);
    lv_obj_set_y(ui_Panel3, 99);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labe3 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_labe3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labe3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labe3, 60);
    lv_obj_set_y(ui_labe3, 0);
    lv_obj_set_align(ui_labe3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labe3, "Target:");

    ui_angleValue = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_angleValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_angleValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_angleValue, 103);
    lv_obj_set_y(ui_angleValue, 0);
    lv_obj_set_align(ui_angleValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_angleValue, "90°");

    ui_Panel2 = lv_obj_create(ui_Panel3);
    lv_obj_set_width(ui_Panel2, 40);
    lv_obj_set_height(ui_Panel2, 28);
    lv_obj_set_x(ui_Panel2, -134);
    lv_obj_set_y(ui_Panel2, 0);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xDAE8FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoPin = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_ServoPin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServoPin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ServoPin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ServoPin, "18");
    lv_obj_set_style_text_font(ui_ServoPin, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Panel3);
    lv_obj_set_width(ui_Panel4, 100);
    lv_obj_set_height(ui_Panel4, 28);
    lv_obj_set_x(ui_Panel4, -39);
    lv_obj_set_y(ui_Panel4, 0);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xF12525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 1);
    lv_obj_set_y(ui_Label15, 0);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Vol: 5V");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -102);
    lv_obj_set_y(ui_Label7, 98);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "|");

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 59);
    lv_obj_set_height(ui_Button1, 35);
    lv_obj_set_x(ui_Button1, -114);
    lv_obj_set_y(ui_Button1, 32);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 3);
    lv_obj_set_y(ui_Label10, 0);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "0°");

    ui_Button3 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button3, 59);
    lv_obj_set_height(ui_Button3, 35);
    lv_obj_set_x(ui_Button3, -41);
    lv_obj_set_y(ui_Button3, 32);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 1);
    lv_obj_set_y(ui_Label11, 0);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "45°");

    ui_Button4 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button4, 59);
    lv_obj_set_height(ui_Button4, 35);
    lv_obj_set_x(ui_Button4, 30);
    lv_obj_set_y(ui_Button4, 31);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 3);
    lv_obj_set_y(ui_Label12, 0);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "90°");

    ui_Button5 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button5, 59);
    lv_obj_set_height(ui_Button5, 35);
    lv_obj_set_x(ui_Button5, 102);
    lv_obj_set_y(ui_Button5, 31);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 3);
    lv_obj_set_y(ui_Label13, 0);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "180°");

    ui_Label8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -149);
    lv_obj_set_y(ui_Label8, -30);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "0°");

    ui_Label9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 145);
    lv_obj_set_y(ui_Label9, -30);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "180°");

    ui_angleSlider = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_angleSlider, 0, 180);
    lv_slider_set_value(ui_angleSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_angleSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_angleSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_angleSlider, 243);
    lv_obj_set_height(ui_angleSlider, 22);
    lv_obj_set_x(ui_angleSlider, -7);
    lv_obj_set_y(ui_angleSlider, -29);
    lv_obj_set_align(ui_angleSlider, LV_ALIGN_CENTER);

    lv_obj_set_style_radius(ui_angleSlider, 30, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -4);
    lv_obj_set_y(ui_Label14, -56);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "90°");

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 23);
    lv_obj_set_y(ui_Label2, 99);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "|");

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_angleSlider, ui_event_angleSlider, LV_EVENT_ALL, NULL);

}
